<?php

namespace AndyTruong\Bible\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VerseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerseRepository extends EntityRepository
{

}
