parameters:
#    andy_truong_bible.example.class: AndyTruong\Bundle\BibleBundle\Example

services:
#    andy_truong_bible.example:
#        class: %andy_truong_bible.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
