imports:
    - { resource: config_dev.yml }

parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: vcbible
    database_user: root
    database_password: null
    database_path: var/cache/test/db.sqlite

doctrine:
    dbal:
        path: "%database_path%"

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
