admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonota_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

andytruong_bible_ui:
    resource: "@AndyTruongBibleUIBundle/Resources/config/routing.yml"
    prefix:   /

andytruong_bible:
    resource: "@AndyTruongBibleBundle/Resources/config/routing.yml"
    prefix:   /

andytruong_common:
    resource: '@AndyTruongCommonBundle/Resources/config/routing.yml'
