andy_truong_bible_ui:
    resource: "@AndyTruongBibleUIBundle/Resources/config/routing.yml"
    prefix:   /

andy_truong_bible:
    resource: "@AndyTruongBibleBundle/Resources/config/routing.yml"
    prefix:   /
