andytruong_bible_ui:
    resource: "@AndyTruongBibleUIBundle/Resources/config/routing.yml"
    prefix:   /

andytruong_bible:
    resource: "@AndyTruongBibleBundle/Resources/config/routing.yml"
    prefix:   /

andytruong_common:
    resource: '@AndyTruongCommonBundle/Resources/config/routing.yml'
