parameters:
#    andy_truong_common.example.class: AndyTruong\Bundle\CommonBundle\Example

services:
#    andy_truong_common.example:
#        class: %andy_truong_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
