parameters:
#    andy_truong_bible.example.class: AndyTruong\Bundle\BibleBundle\Example

services:
    atbible.controller.restful:
        class: AndyTruong\Bundle\BibleBundle\Controller\RestfulController
        arguments: ['@doctrine.orm.entity_manager']

#    andy_truong_bible.example:
#        class: %andy_truong_bible.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
