<?php

return [
    ['gen', 'Sáng Thế Ký', 50],
    ['exo', 'Xuất Ê-díp-tô Ký', 40],
    ['lev', 'Lê-vi Ký', 27],
    ['num', 'Dân Số Ký', 36],
    ['deu', 'Phục Truyền Luật Lệ Ký', 34],
    ['jos', 'Giô-suê', 24],
    ['jdg', 'Các Quan Xét', 21],
    ['rut', 'Ru-tơ', 4],
    ['1sa', 'I Sa-mu-ên', 31],
    ['2sa', 'II Sa-mu-ên', 24],
    ['1ki', 'I Các Vua', 22],
    ['2ki', 'II Các Vua', 25],
    ['1ch', 'I Sử Ký', 29],
    ['2ch', 'II Sử Ký', 36],
    ['ezr', 'Ê-xơ-ra', 10],
    ['neh', 'Nê-hê-mi', 13],
    ['est', 'Ê-xơ-tê', 10],
    ['job', 'Gióp', 42],
    ['psa', 'Thi Thiên', 150],
    ['pro', 'Châm Ngôn', 31],
    ['ecc', 'Truyền Đạo', 12],
    ['sng', 'Nhã Ca', 8],
    ['isa', 'Ê-sai', 66],
    ['jer', 'Giê-rê-mi', 52],
    ['lam', 'Ca Thương', 5],
    ['ezk', 'Ê-xê-chi-ên', 48],
    ['dan', 'Đa-ni-ên', 12],
    ['hos', 'Ô-sê', 14],
    ['jol', 'Giô-ên', 3],
    ['amo', 'A-mốt', 9],
    ['oba', 'Áp-đia', 1],
    ['jon', 'Giô-na', 4],
    ['mic', 'Mi-chê', 7],
    ['nam', 'Na-hum', 3],
    ['hab', 'Ha-ba-cúc', 3],
    ['zep', 'Sô-phô-ni', 3],
    ['hag', 'A-ghê', 2],
    ['zec', 'Xa-cha-ri', 14],
    ['mal', 'Ma-la-chi', 4],
    ['mat', 'Ma-thi-ơ', 28],
    ['mrk', 'Mác', 16],
    ['luk', 'Lu-ca', 24],
    ['jhn', 'Giăng', 21],
    ['act', 'Công Vụ Các Sứ Đồ', 28],
    ['rom', 'Rô-ma', 16],
    ['1co', 'I Cô-rinh-tô', 16],
    ['2co', 'II Cô-rinh-tô', 13],
    ['gal', 'Ga-la-ti', 6],
    ['eph', 'Ê-phê-sô', 6],
    ['php', 'Phi-líp', 4],
    ['col', 'Cô-lô-se', 4],
    ['1th', 'I Tê-sa-lô-ni-ca', 5],
    ['2th', 'II Tê-sa-lô-ni-ca', 3],
    ['1ti', 'I Ti-mô-thê', 6],
    ['2ti', 'II Ti-mô-thê', 4],
    ['tit', 'Tít', 3],
    ['phm', 'Phi-lê-môn', 1],
    ['heb', 'Hê-bơ-rơ', 13],
    ['jas', 'Gia-cơ', 5],
    ['1pe', 'I Phi-e-rơ', 5],
    ['2pe', 'II Phi-e-rơ', 3],
    ['1jn', 'I Giăng', 5],
    ['2jn', 'II Giăng', 1],
    ['3jn', 'III Giăng', 1],
    ['jud', 'Giu-đe', 1],
    ['rev', 'Khải Huyền', 22],
];
